# Nombre de la app y puerto del servidor
spring.application.name=biblioexpress
server.port=8080

# Mostrar el mensaje de error completo en la respuesta JSON (util para probar)
server.error.include-message=always
